server:
  port: 8091
spring:
  cloud:
    stream:
      binders:
        defaultRabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 10.10.7.31
                port: 5672
                username: admin
                password: admin
                virtual-host: /
      bindings:
        input:
          group: group-A
          destination: exchange-msg
          content-type: application/json
