server:
  port: 8081
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: route_test_service
          uri: lb://test-service
          predicates:
            - Path=/api/**
eureka:
  client:
    service-url:
      defaultZone: 'http://127.0.0.1:9000/eureka/'
  instance:
    prefer-ip-address: true
